### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by serhiisad** [serhiisad/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by fakefriend123** [comment]
Cool!

**Comment by serhiisad** [comment]
Thanks

**Comment by serhiisad** [comment]
**Primary skills*

- Project management
- complex problem solving
- product thinking
- creative design

**Education**
Bachelor of Science: Computer Information Systems - 2014
Columbia University, NY
**Certifications**
PHP Framework (certificate): Zend, Codeigniter, Symfony.
Programming Languages: JavaScript, HTML5, PHP OOP, CSS, SQL, MySQL.
**Languages**
English – C2
Chinese – A1
German – A2
