### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by serhiisad** [serhiisad/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by fakefriend123** [comment]
Mindblowing description
![image](https://user-images.githubusercontent.com/64903094/81185736-a26d9100-8fba-11ea-993c-b8ffb648d94e.png)

**Comment by serhiisad** [comment]
🤗🤗🤗 Thanks, lol

**Comment by serhiisad** [comment]
Web Developer - 09/2015 to 05/2019
Luna Web Design, New York
•	Cooperate with designers to create clean interfaces and simple, intuitive interactions and experiences.
•	Develop project concepts and maintain optimal workflow.
•	Work with senior developers to manage large, complex design projects for corporate clients.
•	Complete detailed programming and development tasks for front end public and internal websites as well as challenging back-end server code.
•	Carry out quality assurance tests to discover errors and optimize usability.
