### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by serhiisad** [serhiisad/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by fakefriend123** [comment]
Well done, Serhii

**Comment by serhiisad** [comment]
thanks

**Comment by serhiisad** [comment]
Address:
666 Great Portland Street, London W6W 6PQ
Phone:
+44 (0)20 xxx6 8xx5 
Email:
christoper.m@mail.net
