### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by serhiisad** [serhiisad/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by fakefriend123** [comment]
Great job!

**Comment by serhiisad** [comment]
thanks

**Comment by serhiisad** [comment]
<h2>Resume</h2> 
<p>&mdash; Senior Web Developer specializing in front end development. Experienced with all stages of the development cycle for dynamic web projects. Well-versed in numerous programming languages including HTML5, PHP OOP, JavaScript, CSS, MySQL. Strong background in project management and customer relations.</p>
